# Generated by Django 4.1.6 on 2023-02-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, choices=[('choice_1', 'choice_1'), ('choice_2', 'choice_2'), ('choice_3', 'choice_3'), ('choice_4', 'choice_4')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='choice_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='choice_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='choice_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='choice_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
