# Generated by Django 4.1.6 on 2023-02-06 07:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersapp', '0002_alter_answer_answer_alter_mcq_choice_1_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('student', 'question')},
        ),
    ]
